version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
    ports:
      - "3000:3000" # Expose port 3000 for the app